import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { LayoutDefault } from "~/components/layout_default";
import { Box, Text } from "@mantine/core";
import { TableSort } from "~/components/table";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const data = [];

  for (let i = 0; i < 30; i++) {
    const name = "Person " + String(i + 1);
    const email = "person" + String(i + 1) + "@example.com";
    const company = "Company " + String((i % 5) + 1);
    data.push({ name, email, company, id: "id" + String(i) });
  }
  const itemsBreadCrumbs = [
    { title: 'Home', href: '/' },
    { title: 'packages', href: '/packages' },
  ];
  return (
    <>
      <Head>
        <title>Live Track App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutDefault items={itemsBreadCrumbs}>
        <Box>
          <Text>
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </Text>

          <TableSort data={data} />
        </Box>
      </LayoutDefault>
    </>
  );
};

export default Home;
